### ISSUE TITLE
Int lists unsupported in eval

### ISSUE THREAD

**Issue by carmocca** [roy-ht/editdistance#46]
The following code should work: 
```
editdistance.eval([[1, 2], [3, 4]], [])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "editdistance/bycython.pyx", line 11, in editdistance.bycython.eval
  File "editdistance/bycython.pyx", line 15, in editdistance.bycython.eval
TypeError: unhashable type: 'list'
```
The behaviour should be the same as:
```
editdistance.eval(['ab', 'bc'], [])
2 
```
Is this a bug or just not supported? It works using https://github.com/life4/textdistance

Thanks.

**Comment by carmocca** [comment]
Closing due to lack of activity
